name = "explain-runtime"
main = "src/index.js"
compatibility_date = "2026-06-10"

[[kv_namespaces]]
binding = "EXPLAIN_MISSIONS"
id = "fa4cc550dcd94805aeb0e71313b38bef"

[vars]
ALLOWED_ORIGIN = "https://kwilkinsonsales.github.io"
DEFAULT_TTL_SECONDS = "604800"
